/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация
         * @description Создаёт нового пользователя и сразу выставляет JWT access/refresh token в httpOnly cookie.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Вход
         * @description Принимает email **или** username и пароль, выставляет JWT access/refresh token в httpOnly cookie (и роль пользователя в отдельную читаемую подписанную cookie).
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обновление токена
         * @description Читает refresh token из httpOnly cookie и выдаёт новую пару access/refresh (с ротацией — старый refresh token отзывается).
         */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Публичный ключ
         * @description Публичный ключ в формате JWK (ES256), которым подписаны JWT — можно проверить подпись на клиенте, не обращаясь к бэкенду за каждым запросом.
         */
        get: operations["get_public_key_auth_public_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Текущий пользователь
         * @description Возвращает данные авторизованного пользователя по JWT токену.
         */
        get: operations["get_me_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выход из профиля
         * @description Отзывает текущий access и refresh токен авторизованного пользователя
         */
        post: operations["logout_users_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список услуг
         * @description Возвращает все услуги вместе с этапами (stages) и их пунктами (items), отсортированные по полю order.
         */
        get: operations["get_services_services_get"];
        put?: never;
        /**
         * Создать услугу
         * @description Создаёт услугу вместе с этапами (stages) и их пунктами (items). order передавать не нужно — новая услуга автоматически становится последней в списке. Порядок этапов в переданном массиве определяет их порядковый номер — присваивается автоматически по позиции в списке.
         */
        post: operations["create_service_services_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/services/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить порядок услуг
         * @description Принимает массив {id, order} — по одному объекту на каждую существующую услугу — и проставляет order каждой услуге по её id. Ожидается, что фронт всегда присылает записи целиком (все услуги разом). Если среди переданных id есть несуществующий, ничего не меняется и возвращается 404.
         */
        patch: operations["reorder_services_services_reorder_patch"];
        trace?: never;
    };
    "/services/{service_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить услугу
         * @description Удаляет услугу по id. Каскадно удаляются все её этапы (stages) — отдельно чистить их не нужно. Если услуга с таким id не найдена, возвращает 404.
         */
        delete: operations["delete_service_services__service_id__delete"];
        options?: never;
        head?: never;
        /**
         * Обновить услугу
         * @description Обновляет название, описание и этапы (stages) услуги по id. Список stages передаётся целиком и полностью заменяет текущий — порядок в массиве определяет их order. order самой услуги не меняется. Если услуга с таким id не найдена, возвращает 404.
         */
        patch: operations["update_service_services__service_id__patch"];
        trace?: never;
    };
    "/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить тест
         * @description Возвращает тест целиком: секции, вопросы и варианты ответов. Вес (баллы) вариантов ответа в этом ответе не передаётся. Если тест ещё не создан, возвращает 404.
         */
        get: operations["get_test_tests_get"];
        put?: never;
        /**
         * Создать тест
         * @description Создаёт тест целиком вместе с секциями, вопросами и вариантами ответов (включая вес каждого варианта). Порядок секций/вопросов/вариантов в переданных массивах определяет их порядок отображения.
         */
        post: operations["create_test_tests_post"];
        /**
         * Удалить тест
         * @description Удаляет тест. Каскадно удаляются все его секции, вопросы и варианты ответов. Если тест ещё не создан, возвращает 404.
         */
        delete: operations["delete_test_tests_delete"];
        options?: never;
        head?: never;
        /**
         * Обновить тест
         * @description Обновляет название и полностью заменяет секции/вопросы/варианты ответов теста. Если тест ещё не создан, возвращает 404.
         */
        patch: operations["update_test_tests_patch"];
        trace?: never;
    };
    "/tests/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отправить ответы и получить баллы
         * @description Публичная ручка: принимает по одному выбранному варианту ответа на каждый вопрос и возвращает сумму баллов (weight) по каждой категории результата. Если пользователь авторизован (передан cookie с токеном), результат также сохраняется в его профиль. Если тест не найден — 404. Если передан несуществующий вопрос/вариант или на один вопрос передано больше одного ответа — 400.
         */
        post: operations["submit_test_tests_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{file_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve Media */
        get: operations["serve_media_media__file_path__get"];
        put?: never;
        post?: never;
        /**
         * Удалить файл
         * @description Удаляет файл из медиахранилища.
         */
        delete: operations["delete_media_media__file_path__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Загрузить файл
         * @description Загружает файл в медиахранилище и возвращает его путь (`/media/<имя_файла>`) для использования в других полях. Разрешённые расширения: jpg, jpeg, png, webp, avif, gif, svg. Максимальный размер — 10 МБ.
         */
        post: operations["upload_media_media_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить содержимое вкладки «Обо мне»
         * @description Возвращает промо-текст (тизер на главной) и полный текст страницы «Обо мне» на русском и английском.
         */
        get: operations["get_about_about_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Обновить содержимое вкладки «Обо мне»
         * @description Обновляет промо-текст и полный текст на русском и английском. HTML санитизируется на сервере. Предыдущая версия сохраняется в историю ревизий.
         */
        patch: operations["update_about_about_patch"];
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список кейсов
         * @description Возвращает все кейсы, отсортированные по полю order.
         */
        get: operations["get_cases_cases_get"];
        put?: never;
        /**
         * Создать кейс
         * @description Создаёт кейс. Принимает multipart/form-data: текстовые поля названия/описания на русском и английском и файл изображения (jpg/jpeg/png/webp/avif/gif/svg, до 10 МБ). order передавать не нужно — новый кейс автоматически становится последним в списке.
         */
        post: operations["create_case_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Изменить порядок кейсов
         * @description Принимает массив {id, order} — по одному объекту на каждый существующий кейс — и проставляет order каждому кейсу по его id. Ожидается, что фронт всегда присылает записи целиком (все кейсы разом). Если среди переданных id есть несуществующий, ничего не меняется и возвращается 404.
         */
        put: operations["reorder_cases_cases_reorder_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить кейс
         * @description Удаляет кейс по id вместе с его файлом изображения. Если кейс с таким id не найден, возвращает 404.
         */
        delete: operations["delete_case_cases__case_id__delete"];
        options?: never;
        head?: never;
        /**
         * Обновить кейс
         * @description Обновляет название, описание и (опционально) изображение кейса по id. Принимает multipart/form-data, как и создание. Файл изображения необязателен — если не передан, текущая картинка остаётся без изменений; если передан, старый файл удаляется. order не меняется. Если кейс с таким id не найден, возвращает 404.
         */
        patch: operations["update_case_cases__case_id__patch"];
        trace?: never;
    };
    "/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список материалов библиотеки
         * @description Возвращает все материалы библиотеки, отсортированные по полю order.
         */
        get: operations["get_library_library_get"];
        put?: never;
        /**
         * Добавить материал
         * @description Добавляет материал библиотеки. Принимает multipart/form-data: текстовые поля названия/описания на русском и английском, файл обложки (jpg/jpeg/png/webp/avif/gif/svg, до 10 МБ) и файл документа (pdf/doc/docx/xls/xlsx/ppt/pptx, до 10 МБ) — оба необязательны. order передавать не нужно — новый материал автоматически становится последним в списке.
         */
        post: operations["create_library_item_library_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Изменить порядок материалов
         * @description Принимает массив {id, order} — по одному объекту на каждый существующий материал — и проставляет order каждому по его id. Ожидается, что фронт всегда присылает записи целиком (все материалы разом). Если среди переданных id есть несуществующий, ничего не меняется и возвращается 404.
         */
        put: operations["reorder_library_library_reorder_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/library/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить материал
         * @description Удаляет материал по id вместе с его файлами (обложка и документ). Если материал с таким id не найден, возвращает 404.
         */
        delete: operations["delete_library_item_library__item_id__delete"];
        options?: never;
        head?: never;
        /**
         * Обновить материал
         * @description Обновляет название, описание и (опционально) обложку/документ материала по id. Принимает multipart/form-data, как и создание. Файлы необязательны — если не переданы, текущие остаются без изменений; если переданы, старые файлы удаляются. order не меняется. Если материал с таким id не найден, возвращает 404.
         */
        patch: operations["update_library_item_library__item_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AboutRead */
        AboutRead: {
            promo: components["schemas"]["Bilingual"];
            full: components["schemas"]["Bilingual"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AboutUpdate */
        AboutUpdate: {
            promo: components["schemas"]["Bilingual"];
            full: components["schemas"]["Bilingual"];
        };
        /** AnswerItem */
        AnswerItem: {
            /** Question Id */
            question_id: number;
            /** Option Id */
            option_id: number;
        };
        /** Bilingual */
        Bilingual: {
            /** Ru */
            ru: string;
            /** En */
            en: string;
        };
        /** BilingualOptional */
        BilingualOptional: {
            /** Ru */
            ru?: string | null;
            /** En */
            en?: string | null;
        };
        /** Body_create_case_cases_post */
        Body_create_case_cases_post: {
            /** Title Ru */
            title_ru: string;
            /** Title En */
            title_en: string;
            /** Description Ru */
            description_ru?: string | null;
            /** Description En */
            description_en?: string | null;
            /** Image */
            image?: string | null;
        };
        /** Body_create_library_item_library_post */
        Body_create_library_item_library_post: {
            /** Title Ru */
            title_ru: string;
            /** Title En */
            title_en: string;
            /** Description Ru */
            description_ru?: string | null;
            /** Description En */
            description_en?: string | null;
            /** Image */
            image?: string | null;
            /** Document */
            document?: string | null;
        };
        /** Body_update_case_cases__case_id__patch */
        Body_update_case_cases__case_id__patch: {
            /** Title Ru */
            title_ru: string;
            /** Title En */
            title_en: string;
            /** Description Ru */
            description_ru?: string | null;
            /** Description En */
            description_en?: string | null;
            /** Image */
            image?: string | null;
        };
        /** Body_update_library_item_library__item_id__patch */
        Body_update_library_item_library__item_id__patch: {
            /** Title Ru */
            title_ru: string;
            /** Title En */
            title_en: string;
            /** Description Ru */
            description_ru?: string | null;
            /** Description En */
            description_en?: string | null;
            /** Image */
            image?: string | null;
            /** Document */
            document?: string | null;
        };
        /** Body_upload_media_media_upload_post */
        Body_upload_media_media_upload_post: {
            /** File */
            file: string;
        };
        /** CaseOrderItem */
        CaseOrderItem: {
            /** Id */
            id: number;
            /** Order */
            order: number;
        };
        /** CaseRead */
        CaseRead: {
            /** Id */
            id: number;
            /** Order */
            order: number;
            title: components["schemas"]["Bilingual"];
            description: components["schemas"]["BilingualOptional"];
            /** Image */
            image: string | null;
        };
        /** CategoryCreate */
        CategoryCreate: {
            title: components["schemas"]["Bilingual"];
            /** Questions */
            questions?: components["schemas"]["QuestionCreate"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LibraryOrderItem */
        LibraryOrderItem: {
            /** Id */
            id: number;
            /** Order */
            order: number;
        };
        /** LibraryRead */
        LibraryRead: {
            /** Id */
            id: number;
            /** Order */
            order: number;
            title: components["schemas"]["Bilingual"];
            description: components["schemas"]["BilingualOptional"];
            /** Image */
            image: string | null;
            /** Document */
            document: string | null;
        };
        /** MediaUploadRead */
        MediaUploadRead: {
            /** Url */
            url: string;
        };
        /** OptionAdminRead */
        OptionAdminRead: {
            /** Id */
            id: number;
            text: components["schemas"]["Bilingual"];
            /** Category */
            category: string;
            /** Weight */
            weight: number;
        };
        /** OptionCreate */
        OptionCreate: {
            text: components["schemas"]["Bilingual"];
            /** Weight */
            weight: number;
            /** Category */
            category: string;
        };
        /** OptionRead */
        OptionRead: {
            /** Id */
            id: number;
            text: components["schemas"]["Bilingual"];
            /** Category */
            category: string;
        };
        /** PublicKeyRead */
        PublicKeyRead: {
            /** Kty */
            kty: string;
            /** Crv */
            crv: string;
            /** X */
            x: string;
            /** Y */
            y: string;
            /** Alg */
            alg: string;
        };
        /** QuestionAdminRead */
        QuestionAdminRead: {
            /** Id */
            id: number;
            text: components["schemas"]["Bilingual"];
            /** Options */
            options: components["schemas"]["OptionAdminRead"][];
        };
        /** QuestionCreate */
        QuestionCreate: {
            text: components["schemas"]["Bilingual"];
            /** Options */
            options?: components["schemas"]["OptionCreate"][];
        };
        /** QuestionRead */
        QuestionRead: {
            /** Id */
            id: number;
            text: components["schemas"]["Bilingual"];
            /** Options */
            options: components["schemas"]["OptionRead"][];
        };
        /** SectionAdminRead */
        SectionAdminRead: {
            /** Id */
            id: number;
            title: components["schemas"]["Bilingual"];
            /** Questions */
            questions: components["schemas"]["QuestionAdminRead"][];
        };
        /** SectionRead */
        SectionRead: {
            /** Id */
            id: number;
            title: components["schemas"]["Bilingual"];
            /** Questions */
            questions: components["schemas"]["QuestionRead"][];
        };
        /** ServiceCreate */
        ServiceCreate: {
            title: components["schemas"]["Bilingual"];
            description: components["schemas"]["Bilingual"];
            /** Stages */
            stages?: components["schemas"]["StageCreate"][];
        };
        /** ServiceOrderItem */
        ServiceOrderItem: {
            /** Id */
            id: number;
            /** Order */
            order: number;
        };
        /** ServiceRead */
        ServiceRead: {
            /** Id */
            id: number;
            /** Order */
            order: number;
            title: components["schemas"]["Bilingual"];
            description: components["schemas"]["Bilingual"];
            /** Stages */
            stages: components["schemas"]["StageRead"][];
        };
        /** StageCreate */
        StageCreate: {
            title: components["schemas"]["Bilingual"];
            /** Items */
            items?: components["schemas"]["Bilingual"][];
        };
        /** StageRead */
        StageRead: {
            title: components["schemas"]["Bilingual"];
            /** Items */
            items: components["schemas"]["Bilingual"][];
        };
        /** StatusResponse[AboutRead] */
        StatusResponse_AboutRead_: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data?: components["schemas"]["AboutRead"] | null;
        };
        /** StatusResponse[CaseRead] */
        StatusResponse_CaseRead_: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data?: components["schemas"]["CaseRead"] | null;
        };
        /** StatusResponse[LibraryRead] */
        StatusResponse_LibraryRead_: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data?: components["schemas"]["LibraryRead"] | null;
        };
        /** StatusResponse[MediaUploadRead] */
        StatusResponse_MediaUploadRead_: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data?: components["schemas"]["MediaUploadRead"] | null;
        };
        /** StatusResponse[NoneType] */
        StatusResponse_NoneType_: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data?: null;
        };
        /** StatusResponse[PublicKeyRead] */
        StatusResponse_PublicKeyRead_: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data?: components["schemas"]["PublicKeyRead"] | null;
        };
        /** StatusResponse[ServiceRead] */
        StatusResponse_ServiceRead_: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data?: components["schemas"]["ServiceRead"] | null;
        };
        /** StatusResponse[TestAdminRead] */
        StatusResponse_TestAdminRead_: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data?: components["schemas"]["TestAdminRead"] | null;
        };
        /** StatusResponse[TestRead] */
        StatusResponse_TestRead_: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data?: components["schemas"]["TestRead"] | null;
        };
        /** StatusResponse[TestResultRead] */
        StatusResponse_TestResultRead_: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data?: components["schemas"]["TestResultRead"] | null;
        };
        /** StatusResponse[UserRead] */
        StatusResponse_UserRead_: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            data?: components["schemas"]["UserRead"] | null;
        };
        /** StatusResponse[list[CaseRead]] */
        StatusResponse_list_CaseRead__: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data?: components["schemas"]["CaseRead"][] | null;
        };
        /** StatusResponse[list[LibraryRead]] */
        StatusResponse_list_LibraryRead__: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data?: components["schemas"]["LibraryRead"][] | null;
        };
        /** StatusResponse[list[ServiceRead]] */
        StatusResponse_list_ServiceRead__: {
            /** Success */
            success: boolean;
            /**
             * Message
             * @default
             */
            message: string;
            /** Data */
            data?: components["schemas"]["ServiceRead"][] | null;
        };
        /** TestAdminRead */
        TestAdminRead: {
            /** Id */
            id: number;
            title: components["schemas"]["Bilingual"];
            /** Sections */
            sections: components["schemas"]["SectionAdminRead"][];
        };
        /** TestCreate */
        TestCreate: {
            title: components["schemas"]["Bilingual"];
            /** Sections */
            sections?: components["schemas"]["CategoryCreate"][];
        };
        /** TestRead */
        TestRead: {
            /** Id */
            id: number;
            title: components["schemas"]["Bilingual"];
            /** Sections */
            sections: components["schemas"]["SectionRead"][];
        };
        /** TestResultRead */
        TestResultRead: {
            /** Scores */
            scores: {
                [key: string]: number;
            };
        };
        /** TestSubmitRequest */
        TestSubmitRequest: {
            /** Answers */
            answers?: components["schemas"]["AnswerItem"][];
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * @example user@example.com
             */
            email?: string | null;
            /**
             * Username
             * @example john_doe
             */
            username: string;
            /**
             * Password
             * @example strongpassword123
             */
            password: string;
        };
        /** UserLogin */
        UserLogin: {
            /**
             * Login
             * @description Email или username
             * @example john_doe
             */
            login: string;
            /**
             * Password
             * @example strongpassword123
             */
            password: string;
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /** Email */
            email: string | null;
            /** Username */
            username: string;
            /** Is Active */
            is_active: boolean;
            /** Role */
            role: string;
            /** Test Result */
            test_result?: {
                [key: string]: number;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_UserRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLogin"];
            };
        };
        responses: {
            /** @description Успешный вход */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_UserRead_"];
                };
            };
            /** @description Неверный логин или пароль */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_UserRead_"];
                };
            };
            /** @description Refresh token отсутствует, истёк или отозван */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_public_key_auth_public_key_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_PublicKeyRead_"];
                };
            };
        };
    };
    get_me_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_UserRead_"];
                };
            };
        };
    };
    logout_users_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_UserRead_"];
                };
            };
        };
    };
    get_services_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_list_ServiceRead__"];
                };
            };
        };
    };
    create_service_services_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_ServiceRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_services_services_reorder_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceOrderItem"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_list_ServiceRead__"];
                };
            };
            /** @description Одна или несколько услуг не найдены */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_service_services__service_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_NoneType_"];
                };
            };
            /** @description Услуга не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_service_services__service_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_ServiceRead_"];
                };
            };
            /** @description Услуга не найдена */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_test_tests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_TestRead_"];
                };
            };
            /** @description Тест не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_test_tests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_TestAdminRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_test_tests_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_NoneType_"];
                };
            };
            /** @description Тест не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_test_tests_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_TestAdminRead_"];
                };
            };
            /** @description Тест не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_test_tests_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_TestResultRead_"];
                };
            };
            /** @description Некорректные ответы */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Тест не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_media_media__file_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_media_media__file_path__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                file_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_NoneType_"];
                };
            };
            /** @description Файл не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_media_media_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_media_media_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_MediaUploadRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_about_about_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_AboutRead_"];
                };
            };
        };
    };
    update_about_about_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AboutUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_AboutRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_cases_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_list_CaseRead__"];
                };
            };
        };
    };
    create_case_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_case_cases_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_CaseRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_cases_cases_reorder_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseOrderItem"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_list_CaseRead__"];
                };
            };
            /** @description Один или несколько кейсов не найдены */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_NoneType_"];
                };
            };
            /** @description Кейс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_case_cases__case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_update_case_cases__case_id__patch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_CaseRead_"];
                };
            };
            /** @description Кейс не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_library_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_list_LibraryRead__"];
                };
            };
        };
    };
    create_library_item_library_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_library_item_library_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_LibraryRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_library_library_reorder_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryOrderItem"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_list_LibraryRead__"];
                };
            };
            /** @description Один или несколько материалов не найдены */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_library_item_library__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_NoneType_"];
                };
            };
            /** @description Материал не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_library_item_library__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_update_library_item_library__item_id__patch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse_LibraryRead_"];
                };
            };
            /** @description Материал не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
