"""link_stages_to_services

Revision ID: 1a840d78d6ef
Revises: 972b6cf434ce
Create Date: 2026-07-22 17:41:24.596753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1a840d78d6ef'
down_revision: Union[str, None] = '972b6cf434ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column(
            'items',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
            nullable=False,
        ))
        batch_op.alter_column('title_ru',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_stages_title_en'))
        batch_op.drop_index(batch_op.f('ix_stages_title_ru'))
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_stages_title_ru'), ['title_ru'], unique=True)
        batch_op.create_index(batch_op.f('ix_stages_title_en'), ['title_en'], unique=True)
        batch_op.alter_column('title_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('title_ru',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('items')
        batch_op.drop_column('order')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
