"""stages_descr_to_array

Revision ID: 972b6cf434ce
Revises: ee0d5d5b0005
Create Date: 2026-07-22 17:04:53.847507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '972b6cf434ce'
down_revision: Union[str, None] = 'ee0d5d5b0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ru_descr', sa.String(), nullable=True),
    sa.Column('en_descr', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('en_descr'),
    sa.UniqueConstraint('ru_descr')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)

    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('ru_descr', sa.String(), nullable=True),
    sa.Column('en_descr', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stages_title_en'), ['title_en'], unique=True)
        batch_op.create_index(batch_op.f('ix_stages_title_ru'), ['title_ru'], unique=True)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=True),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('ru_descr', sa.String(), nullable=True),
    sa.Column('en_descr', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('en_descr'),
    sa.UniqueConstraint('ru_descr')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_title_en'), ['title_en'], unique=True)
        batch_op.create_index(batch_op.f('ix_services_title_ru'), ['title_ru'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_title_ru'))
        batch_op.drop_index(batch_op.f('ix_services_title_en'))
        batch_op.drop_index(batch_op.f('ix_services_id'))

    op.drop_table('services')
    with op.batch_alter_table('stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stages_title_ru'))
        batch_op.drop_index(batch_op.f('ix_stages_title_en'))
        batch_op.drop_index(batch_op.f('ix_stages_id'))

    op.drop_table('stages')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    # ### end Alembic commands ###
