"""add_approach_title_to_services

Revision ID: a07fdb762a70
Revises: 1a840d78d6ef
Create Date: 2026-07-22 17:49:42.544238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a07fdb762a70'
down_revision: Union[str, None] = '1a840d78d6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appr_title_ru', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('appr_title_en', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('appr_title_en')
        batch_op.drop_column('appr_title_ru')

    # ### end Alembic commands ###
