"""add_deploy_test_table

Revision ID: af15b2193cd4
Revises: 1dbfe698c53f
Create Date: 2026-08-04 09:05:49.059571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af15b2193cd4'
down_revision: Union[str, None] = '1dbfe698c53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deploy_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deploy_test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deploy_test_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deploy_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deploy_test_id'))

    op.drop_table('deploy_test')
    # ### end Alembic commands ###
