"""add quiz tests tables

Revision ID: dda912a4f57a
Revises: d4e7b9c1f0a5
Create Date: 2026-07-31 12:14:59.744622

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "dda912a4f57a"
down_revision: Union[str, None] = "d4e7b9c1f0a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tests_id"), ["id"], unique=False)

    op.create_table(
        "test_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("test_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["test_id"], ["tests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_categories_id"), ["id"], unique=False)

    op.create_table(
        "test_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["test_categories.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_questions_id"), ["id"], unique=False)

    op.create_table(
        "test_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"], ["test_questions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("test_options", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_options_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_options", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_options_id"))

    op.drop_table("test_options")
    with op.batch_alter_table("test_questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_questions_id"))

    op.drop_table("test_questions")
    with op.batch_alter_table("test_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_categories_id"))

    op.drop_table("test_categories")
    with op.batch_alter_table("tests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tests_id"))

    op.drop_table("tests")
    # ### end Alembic commands ###
