"""add_role_to_user

Revision ID: ee0d5d5b0005
Revises: 669f09f02bfc
Create Date: 2026-07-13 11:30:36.404079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee0d5d5b0005'
down_revision: Union[str, None] = '669f09f02bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
